name: LPointManager
version: "1.0.0"
author: "lowliver"
api: ["3.2.0", "3.3.0"]
main: LPointManager\LPointManager

commands: 
 포인트: 
  description: 자신의 포인트를 확인합니다.
  usage: /포인트
 내포인트: 
  description: 자신의 포인트를 확인합니다.
  usage: /내포인트
 포인트보내기: 
  description: 자신의 포인트를 플레이어에게 줍니다.
  usage: /포인트보내기
 포인트순위: 
  description: 포인트 순위를 확인합니다.
  usage: /포인트순위
 포인트설정: 
  description: 플레이어의 포인트를 설정합니다.
  usage: /포인트설정
 포인트추가: 
  deacription: 플레이의 포인트를 추가합니다.
  usage: /포인트추가
 포인트뺏기: 
  description: 플레이의 포인트를 뺏습니다.
  usage: /포인트뺏기 